### PR TITLE
Make the module Python3 compatible

### PR DESCRIPTION
**Pull request by jkrueger1**
The code is not fully python3 compatible. It's able to be imported without any error message, but the access to the NeXus library creates some errors.

### CODE REVIEW

**Comment by rayosborn** [comment]
Thanks for submitting this, although I can't test it myself because I don't have the C API installed any more. I thought I should mention that the nexusformat package (https://github.com/nexpy/nexusformat), which is HDF5 only, is already Python 3 compatible. Do you need access to HDF4 and XML? At some point, we need to decide whether to keep both versions going.

**Comment by jkrueger1** [comment]
I also tried the https://github.com/nexpy/nexusformat module and I found out, that files written with this version could not be read back by the NeXuS C API library. Therefore I took this version and it made it.
For us the HDF5 support is sufficient, since we do not have any HDF4/XML based NeXuS data files.

**Comment by rayosborn** [comment]
If the nexpy/nexusformat API produces files that the C-API cannot read, that is a very serious issue that we should urgently address. It is either a bug in one of the APIs or a design incompatibility. Do you have examples of files that could not be read? We should raise an issue on both Githubs.

**Comment by jkrueger1** [comment]
I attach now a archive containing three files:
- the python source code writing the NeXuS file
- NeXuS data file written with the nxs python module from the nexusformat/python-nxs (mynexus_nxs.nxs)
- NeXuS data file written with the nexus module from nexpy/nexusformat (mynexus_nexusformat.nxs)

Using the current version of the NeXuS C API including the F90 FORTRAN code (for nxdump) all works fine for the python-nxs written file, but not for the nexpy nexus module written file.

What also has to be metioned is the complete different file size, which differs enormously (could be explained if the data are compressed written by default in the nexpy format)

[nexus.zip](https://github.com/nexusformat/python-nxs/files/228082/nexus.zip)

**Comment by prjemian** [comment]
In this file _mynexus_nexusformat.nxs_, the _signal_ attribute is used incorrectly in the _NXdata_ group.  There should be exactly and only one field with the _signal_ attribute and its value should be **1**, not _effiiency_ as it appears.  (This would be according to the _Version 2_ pattern as described in the NeXus manual: http://download.nexusformat.org/doc/html/datarules.html#version-2 - it is recommended for new data files to use the Version 3 pattern as described on the same web page.)

**Comment by prjemian** [comment]
In this file _mynexus_nxs.nxs_, there is no _NXdata_ group that is a child of the _NXentry_ group.  One way towards making this file compliant with the NeXus standard would be to link the _/entry/instrument/detector/data_ group to _/entry/data_.

This file **ALSO** has the same incorrect use of the _signal_ attribute, as noted above.

Neither of these files is compliant with the NeXus standard.  That the NAPI accepts either is laudable, yet does not imply they are written per the standard.

**Comment by rayosborn** [comment]
Any array over a size of 10000 elements will automatically be compressed, using 'gzip' by default because it is universally available. I worried that we had used 'lzf', which has better performance, and perhaps the lzf library wasnt available, but I could tell that it was gzip: 

```
>>> mynexus_nexusformat.nxfile['entry/instrument/detector/data/data'].compression
'gzip'
```

Still, that is a candidate for the failure. Is it possible that your version of HDF5 doesn't have the gzip library module available? 

The other major difference, which showed up when doing a diff of the h5dump outputs, is that the nexusformat module uses variable length strings for text, which allows text fields to be replaced without worrying about the string length, and text is encoded as UTF-8 instead of ASCII. Perhaps Mark K., or someone else familiar with the NAPI, can let us know if either should cause a problem.

**Comment by rayosborn** [comment]
Bingo! It's the variable-length strings that are the problem. It turns out that my version of nxbrowse does work. Reading the two files, I get with `mynexus_nxs.nxs`:

```
NX/entry> read title
  title[8] (NX_CHAR) = detector
```

but with `mynexus_nexusformat.nxs`:

```
NX/entry> read title
  ERROR: unable to read dims 
```

I would argue that this counts as a NAPI bug, unless there is something in the NeXus definitions that forbids the use of variable-length strings. I was going to post an issue, but it looks as if one has been open for a few years now - nexusformat/code#329. Perhaps, this should now rise up the priority list. 

It's not directly relevant to this pull request though, if others are able to test that it works.

**Pull request merged**
